before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: Bk0LFuv17wKIECxLaRfQob+6Ad7ekfIBIhxPnK0/9lDmYyd5wONk4Y34PDDhFlSSPbf2SPWrb5NtmlwSidpO+Mk3mj5EC03HnRfFlK4YHscrNxOkbwkNsODlzILU1YAibDtOEk4lmcN9eQCN2hjStuisyhZFiG3A8yGacoZfWKuWidlaKqux07Y07I+CI078VXLtVm6si1losWsURuFTNZ6McHZ2D6FxEaEWGv5ZxbJEfLgAPN9ps88+EuQ06KmRB3M8GLE4bLqwub0HQ4AKnmn1gSgtgcCMQNOInslfoGr0sDXfGUacTTW+c43QGUzXgAvuWppvVKz0KbhZAtRCXD8xD8SVQhFRzs1CrmwgzKifG6Qsfvs1rgQ1anQyrMvJO4cdw3lZDwSZ4uWIZaSBVP1p3HWrZs5Aa5C8wb4pKFtuWDkbHE07flOG5/izUy1RjiXsVyZH3YoES42+dVlqHrcqMYn/addkEkblNn9xlUmknHZmiFwJYmLb6tNpjyw+LfYaPGEPynSXPKSYQA6uNGcJCazMO/FAT1RtfPt/Z1txdkr1K0wcd4bcD0j9aZP2PvhCpYjLHRgIiK8bmClOWMVZxDz19vk/PZHKq9/xjGsduIzO6RHabO5Kwn9uYr2DL5lq0H6mLeHD/vGwb0bd8CIFszfxXBupD6H7jPsDsBc= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
